services:
  - type: web
    name: aisocial-client
    env: node
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
  - type: web
    name: aisocial-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
